language: java

# we have to override the default version 11
jdk: openjdk8

# speeding up later downloads
cache: 
  directories:
    - $HOME/.m2

# our Java project resides in a subfolder, so before any important script runs
# we change to this directory
before_install: cd issuetracker
# In a Maven project we do not need to separately install the dependencies, 
# because it will install it as a part of the testing process automatically,
# so we can skip this step
install: true

# Here we override the default test script, which is: ./mvnw -B test
script: mvn -B test  # mvn clean install would work, too
deploy:
  # do not change the working directory
  skip_cleanup: true

  # use Heroku
  provider: heroku

  # Read below
  api_key:
    secure: "BsaigBzJOQLuWth/UqVxoes3ZMXufn/4niHmFTkCpeOrZQZSMet5+/ElQyOR1hUeDowdfdnOUO0YnuTvGYbc5hwNkj1z3e7MPvUmvuxCR/MNcTHjwlur/7SAvATDLF9Rqwt92idQTeYndCuukUMac1Z98etVdHzPB0erXmWIWNy/Ms4qpRSOSRv/VXp+nsJ6YxMYaUgj5HkBaKIEpIgu/jl8emyAuQpgq70QeejIFFTpLR10+CzqViLc7W44EaAR++03Ri226uTT576CSImqJVH06nerzb8nNDo0gG5Qx/r9ERr9OoitsZkq26PKTGYCtoI7iOVaz4qgjipuxeyxiI3+oHrP8boKigPe/V3ABT+PAx3rjJDIibZht551Lcvsvsl9GPVCrDgwDQuzAApRJGIM69PGH5kglHXp3hJr3kE7S0nU/t5wZV0RzpGAOPiG0FHZBNxcHjShxGJLe+k0qr8Z1ezvtDXrf7ybstyajG6cj3bab2zww55Ey/NstwdY/Jj/Q6oX46yMYkxBW6Nu0zGD8/CPx19X2AconOmDb6pn2/tR9q9h5fcbOuwFUuewmR43PbWQOwi3rzAkHMuFiHE12s5sifEsyc1edK0u2qWK5NqptAkpXuIkA14Wu9JVZYmBzDFC3eXCOwFL5Rm0Lc6c/Yh9e1yhLMuSFaAFVRg="
  
  # App name on Heroku
  app: fullstack-2020-21-1

  # Deploy if there were changes on the main branch
  on: master
